version: '3'

services:
  proxy:
    image: "nginx"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  server1:
    image: "httpd"
    volumes:
      - ./server1:/usr/local/apache2/htdocs

  server2:
    image: "httpd"
    volumes:
      - ./server2:/usr/local/apache2/htdocs


# /etc/hosts
# 127.0.0.1       server1.company.com
# 127.0.0.1       server2.company.com